name: Update Download Count

on:
  repository_dispatch:
    types: [increment_download]

jobs:
  update-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update download count
        run: |
          count=$(jq '.count + 1' download_count.json)
          echo "{\"count\": $count}" > download_count.json

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update download count" && git push)
